cats_project/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, only: [:index, :show, :new, :create, :edit, :update]

end

cats_project/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

cats_project/app/models/cat.rb
class Cat < ApplicationRecord
    COLORS = ['red','orange','yellow','green','blue','purple','white','brown','black']
    validates :birth_date, :color, :name, :sex, presence:true

    has_many :rental_requests,
        foreign_key: :cat_id,
        class_name: :CatRentalRequest,
        dependent: :destroy
end

cats_project/app/models/cat_rental_request.rb
class CatRentalRequest < ApplicationRecord
    validates :status, inclusion: { in: %w(PENDING APPROVED DENIED)}
    validates :cat_id, :start_date, :end_date, presence: true

    belongs_to :cat,
        foreign_key: :cat_id,
        class_name: :Cat

    def overlapping_requests
        CatRentalRequest.where(cat_id: cat_id).where.not("start_date > :end_date OR end_date < :start_date", start_date:start_date, end_date:end_date).where.not(id: self.id)
    end

    def overlapping_approved_requests
        overlapping_requests.where(status: 'APPROVED')
    end

    def does_not_overlap_approved_request
        !overlapping_approved_requests.exists?
    end
end

cats_project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

cats_project/app/controllers/cats_controller.rb
class CatsController < ApplicationController
    def index
        @cats = Cat.all
        render :index
    end

    def show 
        @cat = Cat.find_by(id: params[:id])
        render :show
    end

    def new
        @cat = Cat.new
        render :new
    end

    def create
        @cat = Cat.new(cat_params)
        if @cat.save
            render :show
        else
            render json: @cat.errors.full_messages, status: :unprocessable_entity
        end
    end

    def edit
        @cat = Cat.find_by(id: params[:id])
        render :edit
    end

    def update
        @cat = Cat.find_by(id: params[:id])
        if @cat.update(cat_params)
            render :show
        else
            render json: @cat.errors.full_messages, status: :unprocessable_entity
        end
    end

    private
    def cat_params
        params.require(:cat).permit(:name, :sex, :color, :birth_date, :description)
    end
end

cats_project/app/helpers/application_helper.rb
module ApplicationHelper
end

cats_project/app/helpers/cats_helper.rb
module CatsHelper
end

cats_project/app/views/cats/_form.html.erb
<% if cat.persisted? %>
    <% action_url = cat_url(cat) %>
    <% button_text = "Update" %>
<% else %>
    <% action_url = cats_url %>
    <% button_text = "Create" %>
<% end %>

<form action="<%= action_url %>" method="POST">
    <% if type == :edit %>
        <input type="hidden" name="_method" value="PATCH">
    <% end %>

    <label for="name">Name:</label>
    <input id="name" type="text" name="cat[name]" value=<%= cat.name %>>

    <% if cat.sex == 'F'%>
        <input id="male" type="radio" name="cat[sex]" value="M">
        <label for="male">Male</label>
        <input id="female" type="radio" name="cat[sex]" value="F" checked>
        <label for="female">Female</label>
    <% else %>
        <input id="male" type="radio" name="cat[sex]" value="M" checked>
        <label for="male">Male</label>
        <input id="female" type="radio" name="cat[sex]" value="F">
        <label for="female">Female</label>
    <% end %>

    <label for="color">Color:</label>
    <select id="color" name="cat[color]">
        <option selected disabled>Select Color</option>
        <% Cat::COLORS.each do |color| %>
            <% if color == cat.color %>
                <option value=<%= color %> selected><%= color.upcase %></option>
            <% else %>
                <option value=<%= color %>><%= color.upcase %></option>
            <% end %>
        <% end %>
    </select>

    <label for="birth_date">Birth Date:</label>
    <input id="birth_date" type="date" name="cat[birth_date]" value=<%= cat.birth_date %>>

    <label>Description:
        <textarea name="cat[description]"><%= cat.description %></textarea>
    </label>

    <input type="submit" value=<%= button_text %>>
    
</form>

cats_project/app/views/cats/edit.html.erb
<h1>Edit a cat:</h1>

<%= render "form", cat: @cat, type: :edit %>

cats_project/app/views/cats/index.html.erb
<h1>All the Cats:</h1>

<ul>
    <% @cats.each do |cat| %>
        <li><a href="<%= cat_url(cat) %>"><%= cat.name %></a></li>
    <% end %>
</ul>

cats_project/app/views/cats/new.html.erb
<h1>Create a cat:</h1>

<%= render "form", cat: @cat, type: :new %>

cats_project/app/views/cats/show.html.erb
<table>
    <thead>
        <tr>
            <th colspan="2"><%= @cat.name %></th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td>BIRTH DATE</td>
            <td><%= @cat.birth_date %></td>
        </tr>
        <tr>
            <td>COLOR</td>
            <td><%= @cat.color.upcase %></td>
        </tr>
        <tr>
            <td>SEX</td>
            <td><%= @cat.sex %></td>
        </tr>
    </tbody>
</table>
<!--
<h1><%= @cat.name %></h1>

<h3>Birth Date: <%= @cat.birth_date %></h3>
<h3>Color: <%= @cat.color %></h3>
<h3>Sex: <%= @cat.sex %></h3>

<p><%= @cat.description %></p>
-->

cats_project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CatsProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>